name: DeepMalNet
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - tqdm
  - pip
  - ipykernel
  - notebook
  - pip:
      - torch       # CPU build; change to torch==2.4.0+cu124 if you want CUDA
      - torchvision # not strictly needed, but good to have
      - torchaudio  # same as above
      - lmdb==1.7.3
      - baker==1.3
      - msgpack==1.1.1
      - msgpack-numpy==0.4.8
      - git+https://github.com/pefe-system/pefe-ief.git@ee1cbc63faf2ffc5a7b5e468de576fe3f9973d72#egg=pefe_ief
      - git+https://github.com/pefe-system/pefe-common.git@ae4c01d8469a731ed9680f3c55e6e740ddbffa00#egg=pefe_common
      - git+https://github.com/laam-egg/EMBER2024@00f69f339f24a07a7b6d9141245749b412933fcc#egg=thrember
